### ISSUE TITLE
New species groups (invasive aliens species groups & informal groups)

### ISSUE THREAD

**Issue by Blodir** [luomus/vieraslajit#3]
Invasive Species Groups (formerly "Harmful Invasive Alien Species")

    National Invasive Species List
    EU Invasive Species List
    Regulated Plant Pests
    Other Harmful Invasive Species  **MX.concernInvasiveSpeciesNotOnOtherLists**

Replace the existing species groups with new groups:

Plants, (old group: HBE.MG2)
Mammals and Birds, (old group: HBE.MG8)
Fish and Crayfish, (uusi: HBE.MG15)  • Kalat ja ravut
Snails, (uusi: HBE.MG16) Etanat
Insects, (uusi: HBE.MG17)  Hyönteiset
Other Invertebrates, (uusi: HBE.MG18) Muut selkärangattomat
Diseases and Pathogens, (uusi: HBE.MG19) • Taudit ja taudinaiheuttajat
Reptiles and amphibians (uusi: HBE.MG20) -  Matelijat ja sammakkoeläimet
Other (uusi; HBE.MG21)  • Muut 

Luke has created a table with the species with new labels: https://helsinkifi-my.sharepoint.com/:x:/g/personal/ellaiho_ad_helsinki_fi/EbUwC07GNMNGk98LBgt4BGYBN7pJQ5_80oNVwj0IY_uKTQ?e=T6HwpD

**Comment by laihoel** [comment]
Message from Ella Ahti:

1. Olemme pohtineet, miten yksinkertaistaa vieraslajit.fin lajiluokittelua helpommin ymmärrettäväksi. Kysyisinkin, onnistuisiko teidän vaihtaa nykyinen luokittelu seuraavanlaiseksi: 

Uusi luokittelu 
Vieraslajiryhmät  (aikaisemmin Haitalliseksi säädetyt vieraslajit)
•	Kansallinen vieraslajiluettelo 
•	EU:n vieraslajiluettelo 
•	Säädetyt kasvintuhoojat 
•	Muut haitalliset vieraslajit

Eliöryhmät  (aikaisemmin vieraslajiryhmät)
•	Kasvit 
•	Nisäkkäät ja linnut 
•	Kalat ja ravut 
•	Matelijat ja sammakkoeläimet 
•	Etanat 
•	Hyönteiset 
•	Muut selkärangattomat 
•	Taudit ja taudinaiheuttajat 
•	Muut 

Käytännössä lajit jaoteltaisiin taksonomisiin ryhmiin ja tehtäisiin uusi ryhmä niille lajeille, joita ei ole säädetty haitallisiksi kansallisesti tai EU:ssa tai eivät ole säädettyjä kasvintuhoojia. Alla myös teksti tämän uuden luokan kuvaukseksi. Liitteenä myös jokainen laji lisättynä uuteen taksonomiseen ryhmään.

""
Suomessa on useita vieraslajeja, joita ei ole säädetty haitallisiksi eli ne eivät kuulu kansalliseen eivätkä EU:n haitallisten vieraslajien luetteloon. Nämä vieraslajit ovat tutkitusti tai potentiaalisesti haitallisia, ja niitä koskee ympäristöön päästämisen kielto.

**Comment by Blodir** [comment]
### Tämänhetkinen lajittelu:

Haitalliset
- Kansallinen luettelo: `adminStatusFilters: MX.controllingRisksOfInvasiveAlienSpecies`
- EU luettelo: `adminStatusFilters: MX.euInvasiveSpeciesList`
- Kasvintuhoojat: `adminStatusFilters: MX.quarantinePlantPest, adminStatusFilters: MX.qualityPlantPest`

Vieraslajiryhmät käyttää https://schema.laji.fi/alt/HBE.invasiveSpeciesMainGroups enumia

Kaikilla on lisäksi `adminStatusFilters: HBE.MG14` (Species shown on Vieraslajit.fi) ja `invasiveSpeciesFilter: true`

### Mitä pitää muuttaa/lisätä:

Mitä "Muut haitalliset vieraslajit" tarkoittaa? `adminStatusFilters: MX.otherInvasiveSpeciesList`?

Uudistetut eliöryhmät kannattaa varmaan lisätä `HBE.invasiveSpeciesMainGroups` enumiin, eli nämä:
• Kalat ja ravut
• Matelijat ja sammakkoeläimet
• Etanat
• Hyönteiset
• Muut selkärangattomat
• Taudit ja taudinaiheuttajat
• Muut

**Comment by Blodir** [comment]
- Muuta otsikko: "Haitalliseksi säädetyt..." -> Vieraslajiryhmät
- Description teksti 
- Muuta otsikko: "Vieraslajiryhmät" -> Eliöryhmät

**Comment by esko-piirainen** [comment]
New portal groups are ready (listed in task description)

Admin status for "Muut haitalliset vieraslajit" is MX.concernInvasiveSpeciesNotOnOtherLists

**Comment by Blodir** [comment]
> ^ping [@Blodir](https://github.com/Blodir)

`HBE.MG14` still if no other `invasiveSpeciesMainGroups` filters are present?
