### ISSUE TITLE
Improve observation map legend

### ISSUE THREAD

**Issue by Blodir** [luomus/vieraslajit#6]
Instead of showing "havaintoja karttanäkymässä yli 2000" in the legend, show "havainnot näkyvät ruutuina kun karttanäkymässä on yli 2000 havaintoa". Show different legends depending on point/aggregate mode.

eg. https://vieraslajit.fi/lajit/MX.52801/

**Comment by Blodir** [comment]
Completed by https://github.com/luomus/vieraslajit/commit/c1f62ec8f7e6e358a2b3cfc2b4abf2cb2170d143

**Comment by wkmor1** [comment]
ping @laihoel
